'\" t
.\"     Title: cryptotab
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/30/2010
.\"    Manual: Cryptsetup Manual
.\"    Source: cryptsetup
.\"  Language: English
.\"
.TH "CRYPTOTAB" "5" "11/30/2010" "cryptsetup" "Cryptsetup Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cryptotab \- static information about crypted filesystems (deprecated)
.SH "SYNOPSIS"
.PP
\fBcryptotab\fR
.RS 4

\fILOOPDEVICE\fR
\fIDEVICE\fR
\fIMOUNTPOINT\fR
\fIFILESYSTEM\fR
\fIALGORITHM\fR[
\fIMOUNTOPTIONS\fR[
\fIINFO\fR]]
.RE
.SH "DESCRIPTION"
.sp
The file \fB/etc/cryptotab\fR contains descriptive informations about encrypted volumes\&. Each volume is described on a separate line; columns on each line are separated by tabs or spaces\&. Lines starting with "\fI#\fR" are comments, empty lines are ignored\&. The order of records in \fBcryptotab\fR is important because the \fB/etc/init\&.d/boot\&.crypto\fR script sequentially iterates through \fBcryptotab\fR entries\&.
.PP
\fILOOPDEVICE\fR
.RS 4
specifies the loop device to use for this mapping, for example
/dev/loop0
.RE
.PP
\fIDEVICE\fR
.RS 4
specifies the block special device that holds the encrypted data
.RE
.PP
\fIMOUNTPOINT\fR
.RS 4
specifies the where the volume should be mounted
.RE
.PP
\fIFILESYSTEM\fR
.RS 4
specifies the file system of the volume
.RE
.PP
\fIALGORITHM\fR
.RS 4
specifies the encryption algorithm to use
.sp
Supported algorithms are
\fItwofish\fR,
\fItwofishSL92\fR
and
\fItwofish256\fR
.RE
.PP
\fIMOUNTOPTIONS\fR
.RS 4
optionally specifies mount option
.RE
.PP
\fIINFO\fR
.RS 4
optionally specifies a string that should be printed when prompting for the passphrase
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
/dev/loop0 /dev/sda6 /secret ext2 twofish256
.fi
.if n \{\
.RE
.\}
.SH "BUGS"
.sp
\fB/etc/cryptotab\fR was designed for use with the deprecated cryptoloop technology and is no longer supported\&. This manual only exists for reference\&. Use \fB/etc/crypttab\fR (note the missing \(lqo\(rq) instead\&. The script \fBconvert_cryptotab\fR may help with this task\&.
.SH "SEE ALSO"
.sp
cryptsetup(8), /etc/crypttab, mount(8)
.SH "AUTHOR"
.sp
Ludwig Nussel <ludwig\&.nussel@suse\&.de>\&.
