#!/bin/sh
# create log suitable for c&p into rpm changes file
if [ -z "$1" ]; then
	set -- remotes/origin/master..master
fi
# no idea why it always prints those commit lines
echo '- boot.crypto:'
git-rev-list --pretty=format:"  * %s" "$@" |grep -v ^commit
